version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - app42.paas.db.username=acp4pogynvaeidfj
      - app42.paas.db.port=8514
      - app42.paas.db.password=jc31d2qyy7h9jv5jn1u9uosjksxzaizw
      - app42.paas.db.host=db
      - app42.paas.db.name=dd
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: dd
      MYSQL_USER: acp4pogynvaeidfj
      MYSQL_PASSWORD: jc31d2qyy7h9jv5jn1u9uosjksxzaizw
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "8514:3306"